export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  SESSION_STATE_CONFLICT: 'SESSION_STATE_CONFLICT',
  PERSISTENCE_ERROR: 'PERSISTENCE_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
